apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tasks-service
  # This is an extra long description
  description: Tasks service which holds everything to do with tasks and task templates
  links:
    - url: https://gitlab.tooling.shipyardtech.com/sylon/platform/tasks-service
      title: Gitlab Repo
      icon: gitlab
  annotations:
    jenkins.io/job-full-name: gitlab-org-scan/sylon%2Fplatform%2Ftasks-service
    gitlab.com/project-id: '4677'
    sonarqube.org/project-key: io.sylon.platform:tasks-service
    newrelic.com/dashboard-guid: MjQ3NTYyMnxWSVp8REFTSEJPQVJEfGRhOjgwNTE2OA
    'backstage.io/kubernetes-label-selector': 'app=tasks-service'
spec:
  type: service
  lifecycle: production
  owner: sylon
  providesApis:
    - tasks-service