apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: composite-service
  description: Composite service api
spec:
  type: openapi
  lifecycle: production
  owner: sylon
  definition:
    $text: https://gitlab.tooling.shipyardtech.com/sylon/platform/composite-service/-/blob/master/api/src/main/resources/swagger/api.yaml