apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-management-service
  description: Tasks service api
spec:
  type: openapi
  lifecycle: production
  owner: sylon
  definition:
    $text: https://gitlab.tooling.shipyardtech.com/sylon/platform/user-management-service/-/blob/master/api/src/main/resources/swagger/api.yaml